wandb_version: 1

batch_size:
  desc: null
  value: 149
delta_es:
  desc: null
  value: 0.0466757223431708
epochs:
  desc: null
  value: 2000
learning_rate:
  desc: null
  value: 0.012323216588359236
patience:
  desc: null
  value: 17
weight_decay_opt:
  desc: null
  value: 0.49112835289576245
_wandb:
  desc: null
  value:
    python_version: 3.7.9
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700800828.54517
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.7.9
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
