wandb_version: 1

batch_size:
  desc: null
  value: 10
delta_es:
  desc: null
  value: 0.044743291430784586
epochs:
  desc: null
  value: 2000
learning_rate:
  desc: null
  value: 0.06510465333316309
patience:
  desc: null
  value: 18
weight_decay_opt:
  desc: null
  value: 0.02883996083150319
_wandb:
  desc: null
  value:
    python_version: 3.7.9
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700801104.769605
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.7.9
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
