wandb_version: 1

batch_size:
  desc: null
  value: 84.85932933339485
delta_es:
  desc: null
  value: 0.02907921666621095
epochs:
  desc: null
  value: 2000
learning_rate:
  desc: null
  value: 0.0016013498380347314
patience:
  desc: null
  value: 4.227234624399534
weight_decay_opt:
  desc: null
  value: 0.23474145506620783
weight_decay:
  desc: null
  value: 0.025
delta_earlyStopping:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.7.9
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700692310.078823
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.7.9
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
