wandb_version: 1

batch_size:
  desc: null
  value: 65
delta_es:
  desc: null
  value: 0.020175349048524503
epochs:
  desc: null
  value: 2000
learning_rate:
  desc: null
  value: 0.005529315075563611
patience:
  desc: null
  value: 12
weight_decay_opt:
  desc: null
  value: 0.103653122324539
_wandb:
  desc: null
  value:
    python_version: 3.7.9
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700802584.725639
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.7.9
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
